name: PPV Scraper Auto Update

on:
  schedule:
    # Every 8 hours
    - cron: "0 */8 * * *"
  workflow_dispatch:  # allow manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install node-fetch puppeteer-extra puppeteer-extra-plugin-stealth moment-timezone

      - name: Run scraper
        run: |
          node scraper.js

      - name: Commit & Push updated playlist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action Bot"

          # Add file only if changed
          if [[ `git status --porcelain` ]]; then
            git add SportsWebcast2.m3u8
            git commit -m "Auto-update playlist (every 8 hours)"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:main
          else
            echo "No changes detected â†’ nothing to commit."
          fi
